mybatis:
  type-aliases-package: com.miaosha.miaosha_1.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/miaosha/miaosha_1/dao/*.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.91.150:3306/miaosha?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=TRUE
    username: root
    password: 1138569314feng.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 1000
      max-wait: 60000
      initial-size: 100
      min-idle: 500
      aop-patterns: com.miaosha.miaosha_4.* # 监控SpringBean
      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
      web-stat-filter: # 监控Web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 监控sql
          slow-sql-millis: 3000
          log-slow-sql: true
          enabled: true
        wall: # 监控防火墙
          enabled: true
          config:
            drop-table-allow: false # 禁止删表


  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

  redis:
    host: 192.168.91.150
    password: xvdf7cuFb0gp2ZqL
    port: 6379
    timeout: 3 # 连接超时时间
    pool-max-total: 1000
    pool-max-wait: 60000

  rabbitmq:
    host: 192.168.91.150
    port: 5672
    username: admin
    password: 123
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: / # 虚拟主机配置
    listener:
      simple:
        concurrency: 10 # 侦听器调用程序线程的最小数量。
        max-concurrency: 10 # 侦听器调用程序线程的最大数量
        prefetch: 1 # 每个消费者可以处理的未确认消息的最大数量。
        auto-startup: true # 自动启动消费者
        default-requeue-rejected: true # 消费失败自动重新排队
      direct:
        retry:
          enabled: true # 重试
          initial-interval: 1000 # 重试间隔
          max-attempts: 3 # 尝试传递消息的最大次数。
          max-interval: 10000 # 尝试之间的最大持续时间
          multiplier: 1.0 # 应用于前一个重试间隔的乘数。


  resources:
    add-mappings: true
    chain: # resolver的相关配置
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/
    cache:
      cachecontrol:
        max-age: 3600
        cache-public: true
        no-cache: false
        no-store: false
        must-revalidate: false


# management是actuator所有的端点
management:
  endpoints:
    enabled-by-default: true # 默认开启所有监控端点
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点
  endpoint:
    health:
      show-details: always
