mybatis:
  type-aliases-package: com.miaosha.miaosha_1.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/miaosha/miaosha_1/dao/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=TRUE
    username: root
    password: 1138569314feng.
    driver-class-name: com.mysql.cj.jdbc.Driver


  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

  redis:
    host: 192.168.91.150
    password: xvdf7cuFb0gp2ZqL
    port: 6379
    timeout: 3 # 连接超时时间
    pool-max-total: 10
    pool-max-idle: 10
    pool-max-wait: 3
